[tool.poetry]
name = "multigrate"
version = "1.0.0"
description = "multiomic data integration for single-cell genomics"
authors = ["Anastasia Litinetskaya <anastasia.litinetskaya@helmholtz-muenchen.de>", "Mohammad Lotfollahi <mohammad.lotfollahi@helmholtz-muenchen.de>"]
homepage = "https://github.com/theislab/multigrate/"
license = "BSD-3-Clause"
readme = "README.md"
packages = [
    { include = "multigrate" }
]


[tool.poetry.dependencies]
python = ">=3.9,<3.11"
scikit-learn = "^1.0.2"
statsmodels = "^0.13.2"
numba = "^0.55.1"
tables = "^3.7.0"
notebook = "^6.4.10"
leidenalg = "^0.8.9"
louvain = "^0.7.1"
scanpy = "^1.9.0"
scvi-tools = "^0.14.6"
torchmetrics = "^0.6.0"
nbconvert = { version = "^6.4.5", optional = true }
nbformat = { version = "^5.3.0", optional = true }
nbsphinx = { version = "^0.8.8", optional = true }
nbsphinx-link = { version = "^1.3.0", optional = true }
pre-commit = { version = "^2.18.1", optional = true }
pydata-sphinx-theme = { version = ">=0.4.0", optional = true }
jupyter = { version = "^1.0.0", optional = true }
ipython = { version = "^8.2.0", optional = true }
python-igraph = { version = "^0.9.9", optional = true }
scanpydoc = { version = "^0.7.7", optional = true }
sphinx = { version = "^4.3.2", optional = true }
sphinx-autodoc-typehints = { version = "^1.17.0", optional = true }
sphinx-rtd-theme = { version = "^1.0.0", optional = true }
typing_extensions = { version = "^4.1.1", optional = true }
adjustText = { version = "^0.7.3", optional = true }
scib = "^1.0.2"

[tool.poetry.extras]
docs = [
    "jinja2<3.0.3",
    "scanpy",
    "sphinx",
    "scanpydoc",
    "nbsphinx",
    "nbsphinx-link",
    "ipython",
    "pydata-sphinx-theme",
    "typing_extensions",
    "sphinx-autodoc-typehints",
    "sphinx_gallery",
    "sphinx-rtd-theme",
]
tutorials = ["scanpy", "leidenalg", "python-igraph"]

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
    "poetry>=1.0",
    "setuptools", # keep it here or "pip install -e" would fail
]